### ISSUE TITLE
Not support spot and point light

### ISSUE THREAD

**Issue by yanhuifair** [candycat1992/NPR_Lab#2]
The current version can only work in directional light (can  only one light ), and there will be no shadow or light in spot and point.   

Like this :
![1](https://cloud.githubusercontent.com/assets/8871751/9432843/3ede37fa-4a5c-11e5-9c08-4f68513ae146.png)
![2](https://cloud.githubusercontent.com/assets/8871751/9432844/4112a362-4a5c-11e5-8234-b90e0cf57f08.png)
![3](https://cloud.githubusercontent.com/assets/8871751/9432845/424a4ed8-4a5c-11e5-9a0a-9db73f898f01.png)
![4](https://cloud.githubusercontent.com/assets/8871751/9432897/fe717988-4a5c-11e5-9051-a1b3c18b8050.png)
![5](https://cloud.githubusercontent.com/assets/8871751/9432898/ff703c20-4a5c-11e5-866b-ddf4d23c5c8f.png)

**Comment by candycat1992** [comment]
I pushed a new commit to fix that. Check it out.

![2015-08-24 14 03 22](https://cloud.githubusercontent.com/assets/5907064/9433712/f0964fd0-4a68-11e5-8e4d-de70ebe9543a.png)

Note: many effects are depend on segmented diffuse term, so when objects move between the edge of point light, the light may flicker.
